---

- name: webapps
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - ruler
    - passwords
    - artwork
    - chat
    - invoices
  tags:
    - webapps

- name: ruler
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: ruler
  tags:
    - ruler

- name: passwords webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: passwords
  tags:
    - passwords

- name: artwork webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: artwork
  tags:
    - artwork

- name: chat webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: chat
  tags:
    - chat

- name: invoices webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: invoices
  tags:
    - invoices

- name: secrets webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: secrets
  tags:
    - secrets

- name: game webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: game
  tags:
    - game

- name: twitter spaces tracker webapp
  hosts: ocean
  become: false
  gather_facts: no
  roles:
    - role: tst
  tags:
    - tst
